### ISSUE TITLE
1_preinstall.md

### ISSUE THREAD

**Issue by rexmabunga** [rexmabunga/SEBC#3]
Connect to Your Instance using Java SSH client directly from browser is not supported in Chrome.
Used Puttygen and Putty to SSH

Using username "ec2-user".
Authenticating with public key "imported-openssh-key"
[ec2-user@ip-172-31-20-33 ~]$ uname -a
Linux ip-172-31-20-33.ap-southeast-2.compute.internal 3.10.0-514.el7.x86_64 #1 SMP Wed Oct 19 11:24:13 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
[ec2-user@ip-172-31-20-33 ~]$

[ec2-user@ip-172-31-20-33 ~]$ sudo sysctl vm.swappiness=1 -w
vm.swappiness = 1

[ec2-user@ip-172-31-20-33 ~]$ df -k
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/xvda2      10473452 1003248   9470204  10% /
devtmpfs         7598116       0   7598116   0% /dev
tmpfs            7486292       0   7486292   0% /dev/shm
tmpfs            7486292   16640   7469652   1% /run
tmpfs            7486292       0   7486292   0% /sys/fs/cgroup
tmpfs            1497260       0   1497260   0% /run/user/1000

[ec2-user@ip-172-31-20-33 ~]$ mount
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime,seclabel)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
devtmpfs on /dev type devtmpfs (rw,nosuid,seclabel,size=7598116k,nr_inodes=1899529,mode=755)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,seclabel)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,seclabel,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,seclabel,mode=755)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,seclabel,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpuacct,cpu)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_prio,net_cls)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
configfs on /sys/kernel/config type configfs (rw,relatime)
/dev/xvda2 on / type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
selinuxfs on /sys/fs/selinux type selinuxfs (rw,relatime)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=32,pgrp=1,timeout=300,minproto=5,maxproto=5,direct)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,seclabel)
mqueue on /dev/mqueue type mqueue (rw,relatime,seclabel)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=1497260k,mode=700,uid=1000,gid=1000)

[ec2-user@ip-172-31-20-33 ~]$ df -k
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/xvda2      10473452 1003272   9470180  10% /
devtmpfs         7598116       0   7598116   0% /dev
tmpfs            7486292       0   7486292   0% /dev/shm
tmpfs            7486292   16640   7469652   1% /run
tmpfs            7486292       0   7486292   0% /sys/fs/cgroup
tmpfs            1497260       0   1497260   0% /run/user/1000

[ec2-user@ip-172-31-20-33 ~]$ sudo /sbin/tune2fs -l /dev/xvda2
tune2fs 1.42.9 (28-Dec-2013)
/sbin/tune2fs: Bad magic number in super-block while trying to open /dev/xvda2
Couldn't find valid filesystem superblock.

[ec2-user@ip-172-31-20-33 ~]$ egrep 'trans|thp' /proc/vmstat
nr_anon_transparent_hugepages 4
thp_fault_alloc 57
thp_fault_fallback 0
thp_collapse_alloc 1
thp_collapse_alloc_failed 0
thp_split 1
thp_zero_page_alloc 0
thp_zero_page_alloc_failed 0

[ec2-user@ip-172-31-20-33 ~]$ sudo vi /etc/sysconfig/grub
GRUB_TIMEOUT=1
GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=true
GRUB_TERMINAL_OUTPUT="console"
GRUB_CMDLINE_LINUX="console=ttyS0,115200n8 console=tty0 net.ifnames=0 crashkernel=auto"
GRUB_DISABLE_RECOVERY="true"
GRUB_CMDLINE_LINUX="transparent_hugepage=never"

[ec2-user@ip-172-31-20-33 ~]$ sudo grub2-mkconfig -o /boot/grub2/grub.cfg
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-3.10.0-514.el7.x86_64
Found initrd image: /boot/initramfs-3.10.0-514.el7.x86_64.img
Found linux image: /boot/vmlinuz-0-rescue-be7a44b4b98e404a8cdcd062c4733c10
Found initrd image: /boot/initramfs-0-rescue-be7a44b4b98e404a8cdcd062c4733c10.img
done
[ec2-user@ip-172-31-20-33 ~]$ sudo reboot

[ec2-user@ip-172-31-20-33 ~]$ cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-3.10.0-514.el7.x86_64 root=UUID=3ed41454-00c8-4803-bf61-2ee88aa54dbf ro transparent_hugepage=never

[ec2-user@ip-172-31-20-33 ~]$ egrep 'trans|thp' /proc/vmstat
nr_anon_transparent_hugepages 0
thp_fault_alloc 0
thp_fault_fallback 0
thp_collapse_alloc 0
thp_collapse_alloc_failed 0
thp_split 0
thp_zero_page_alloc 0
thp_zero_page_alloc_failed 0

[ec2-user@ip-172-31-20-33 ~]$ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9001
        inet 172.31.20.33  netmask 255.255.240.0  broadcast 172.31.31.255
        inet6 fe80::9c:55ff:feb3:8543  prefixlen 64  scopeid 0x20<link>
        ether 02:9c:55:b3:85:43  txqueuelen 1000  (Ethernet)
        RX packets 988  bytes 117149 (114.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 940  bytes 179123 (174.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 68  bytes 6420 (6.2 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 68  bytes 6420 (6.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[ec2-user@ip-172-31-20-33 ~]$ getent networks
default               0.0.0.0
loopback              127.0.0.0
link-local            169.254.0.0
[ec2-user@ip-172-31-20-33 ~]$ getent hosts cloudera.com google.com cnn.com yahoo.com
52.52.13.233    cloudera.com
52.52.119.122   cloudera.com
2404:6800:4006:809::200e google.com
151.101.192.73  cnn.com
151.101.0.73    cnn.com
151.101.64.73   cnn.com
151.101.128.73  cnn.com
2001:4998:c:a06::2:4008 yahoo.com
2001:4998:44:204::a7 yahoo.com
2001:4998:58:c02::a9 yahoo.com

[ec2-user@ip-172-31-20-33 ~]$ service --status-all
netconsole module not loaded
Configured devices:
lo eth0
Currently active devices:
lo eth0
Usage: /etc/init.d/rh-cloud-firstboot {start|stop}
● rhnsd.service - LSB: Starts the Spacewalk Daemon
   Loaded: loaded (/etc/rc.d/init.d/rhnsd; bad; vendor preset: disabled)
   Active: active (running) since Mon 2017-02-13 11:19:23 EST; 24min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 764 ExecStart=/etc/rc.d/init.d/rhnsd start (code=exited, status=0/SUCCESS)
 Main PID: 788 (rhnsd)
   CGroup: /system.slice/rhnsd.service
           └─788 rhnsd
Feb 13 11:19:23 ip-172-31-20-33.ap-southeast-2.compute.internal systemd[1]: Starting LSB: Starts the Spacewalk....
Feb 13 11:19:23 ip-172-31-20-33.ap-southeast-2.compute.internal rhnsd[764]: Starting Spacewalk Daemon: [  OK  ]
Feb 13 11:19:23 ip-172-31-20-33.ap-southeast-2.compute.internal rhnsd[788]: Spacewalk Services Daemon starting....
Feb 13 11:19:23 ip-172-31-20-33.ap-southeast-2.compute.internal systemd[1]: Started LSB: Starts the Spacewalk ....
Hint: Some lines were ellipsized, use -l to show in full.

[ec2-user@ip-172-31-20-33 ~]$ systemctl list-units --type service --all
  UNIT                                   LOAD      ACTIVE   SUB     DESCRIPTION
 NetworkManager.service                 loaded    active   running Network Manager
ntpd.service                           not-found inactive dead    ntpd.service
ntpdate.service                        not-found inactive dead    ntpdate.service
plymouth-quit-wait.service             not-found inactive dead    plymouth-quit-wait.service

[ec2-user@ip-172-31-20-33 ~]$ sudo yum install ntp
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
rhui-REGION-client-config-server-7                       | 2.9 kB     00:00
rhui-REGION-rhel-server-releases                         | 3.5 kB     00:00
rhui-REGION-rhel-server-rh-common                        | 3.8 kB     00:00
(1/7): rhui-REGION-rhel-server-releases/7Server/x86_64/upd | 1.8 MB   00:00
(2/7): rhui-REGION-client-config-server-7/x86_64/primary_d | 5.4 kB   00:00
(3/7): rhui-REGION-rhel-server-rh-common/7Server/x86_64/gr |  104 B   00:00
(4/7): rhui-REGION-rhel-server-releases/7Server/x86_64/gro | 701 kB   00:00
(5/7): rhui-REGION-rhel-server-rh-common/7Server/x86_64/up |  29 kB   00:00
(6/7): rhui-REGION-rhel-server-rh-common/7Server/x86_64/pr | 110 kB   00:00
(7/7): rhui-REGION-rhel-server-releases/7Server/x86_64/pri |  33 MB   00:00
Resolving Dependencies
--> Running transaction check
---> Package ntp.x86_64 0:4.2.6p5-25.el7_3.1 will be installed
--> Processing Dependency: ntpdate = 4.2.6p5-25.el7_3.1 for package: ntp-4.2.6p5-25.el7_3.1.x86_64
--> Processing Dependency: libopts.so.25()(64bit) for package: ntp-4.2.6p5-25.el7_3.1.x86_64
--> Running transaction check
---> Package autogen-libopts.x86_64 0:5.18-5.el7 will be installed
---> Package ntpdate.x86_64 0:4.2.6p5-25.el7_3.1 will be installed
--> Finished Dependency Resolution
Dependencies Resolved
================================================================================
 Package       Arch   Version            Repository                        Size
================================================================================
Installing:
 ntp           x86_64 4.2.6p5-25.el7_3.1 rhui-REGION-rhel-server-releases 547 k
Installing for dependencies:
 autogen-libopts
               x86_64 5.18-5.el7         rhui-REGION-rhel-server-releases  66 k
 ntpdate       x86_64 4.2.6p5-25.el7_3.1 rhui-REGION-rhel-server-releases  85 k
Transaction Summary
================================================================================
Install  1 Package (+2 Dependent packages)
Total download size: 699 k
Installed size: 1.6 M
Is this ok [y/d/N]: y
Downloading packages:
(1/3): autogen-libopts-5.18-5.el7.x86_64.rpm               |  66 kB   00:00
(2/3): ntp-4.2.6p5-25.el7_3.1.x86_64.rpm                   | 547 kB   00:00
(3/3): ntpdate-4.2.6p5-25.el7_3.1.x86_64.rpm               |  85 kB   00:00
--------------------------------------------------------------------------------
Total                                              2.5 MB/s | 699 kB  00:00
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : autogen-libopts-5.18-5.el7.x86_64                            1/3
  Installing : ntpdate-4.2.6p5-25.el7_3.1.x86_64                            2/3
  Installing : ntp-4.2.6p5-25.el7_3.1.x86_64                                3/3
  Verifying  : ntpdate-4.2.6p5-25.el7_3.1.x86_64                            1/3
  Verifying  : ntp-4.2.6p5-25.el7_3.1.x86_64                                2/3
  Verifying  : autogen-libopts-5.18-5.el7.x86_64                            3/3
Installed:
  ntp.x86_64 0:4.2.6p5-25.el7_3.1
Dependency Installed:
  autogen-libopts.x86_64 0:5.18-5.el7    ntpdate.x86_64 0:4.2.6p5-25.el7_3.1
Complete!

[ec2-user@ip-172-31-20-33 ~]$ sudo yum install nscd
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
Resolving Dependencies
--> Running transaction check
---> Package nscd.x86_64 0:2.17-157.el7_3.1 will be installed
--> Processing Dependency: glibc = 2.17-157.el7_3.1 for package: nscd-2.17-157.el7_3.1.x86_64
--> Running transaction check
---> Package glibc.x86_64 0:2.17-157.el7 will be updated
--> Processing Dependency: glibc = 2.17-157.el7 for package: glibc-common-2.17-157.el7.x86_64
---> Package glibc.x86_64 0:2.17-157.el7_3.1 will be an update
--> Running transaction check
---> Package glibc-common.x86_64 0:2.17-157.el7 will be updated
---> Package glibc-common.x86_64 0:2.17-157.el7_3.1 will be an update
--> Finished Dependency Resolution
Dependencies Resolved
================================================================================
 Package      Arch   Version             Repository                        Size
================================================================================
Installing:
 nscd         x86_64 2.17-157.el7_3.1    rhui-REGION-rhel-server-releases 267 k
Updating for dependencies:
 glibc        x86_64 2.17-157.el7_3.1    rhui-REGION-rhel-server-releases 3.6 M
 glibc-common x86_64 2.17-157.el7_3.1    rhui-REGION-rhel-server-releases  11 M
Transaction Summary
================================================================================
Install  1 Package
Upgrade             ( 2 Dependent packages)
Total download size: 15 M
Is this ok [y/d/N]: y
Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
(1/3): nscd-2.17-157.el7_3.1.x86_64.rpm                    | 267 kB   00:00
(2/3): glibc-2.17-157.el7_3.1.x86_64.rpm                   | 3.6 MB   00:00
(3/3): glibc-common-2.17-157.el7_3.1.x86_64.rpm            |  11 MB   00:00
--------------------------------------------------------------------------------
Total                                               26 MB/s |  15 MB  00:00
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Updating   : glibc-common-2.17-157.el7_3.1.x86_64                         1/5
  Updating   : glibc-2.17-157.el7_3.1.x86_64                                2/5
warning: /etc/nsswitch.conf created as /etc/nsswitch.conf.rpmnew
  Installing : nscd-2.17-157.el7_3.1.x86_64                                 3/5
  Cleanup    : glibc-common-2.17-157.el7.x86_64                             4/5
  Cleanup    : glibc-2.17-157.el7.x86_64                                    5/5
  Verifying  : glibc-2.17-157.el7_3.1.x86_64                                1/5
  Verifying  : nscd-2.17-157.el7_3.1.x86_64                                 2/5
  Verifying  : glibc-common-2.17-157.el7_3.1.x86_64                         3/5
  Verifying  : glibc-common-2.17-157.el7.x86_64                             4/5
  Verifying  : glibc-2.17-157.el7.x86_64                                    5/5
Installed:
  nscd.x86_64 0:2.17-157.el7_3.1
Dependency Updated:
  glibc.x86_64 0:2.17-157.el7_3.1     glibc-common.x86_64 0:2.17-157.el7_3.1
Complete!

[ec2-user@ip-172-31-20-33 ~]$ sudo service nscd start
Redirecting to /bin/systemctl start  nscd.service

[ec2-user@ip-172-31-20-33 ~]$ service nscd status
Redirecting to /bin/systemctl status  nscd.service
● nscd.service - Name Service Cache Daemon
   Loaded: loaded (/usr/lib/systemd/system/nscd.service; disabled; vendor preset: disabled)
   Active: active (running) since Mon 2017-02-13 18:15:50 EST; 5s ago
  Process: 5426 ExecStart=/usr/sbin/nscd $NSCD_OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 5427 (nscd)
   CGroup: /system.slice/nscd.service
           └─5427 /usr/sbin/nscd
Feb 13 18:15:50 ip-172-31-20-33.ap-southeast-2.compute.internal nscd[5427]: 5...
Feb 13 18:15:50 ip-172-31-20-33.ap-southeast-2.compute.internal nscd[5427]: 5...
Feb 13 18:15:50 ip-172-31-20-33.ap-southeast-2.compute.internal nscd[5427]: 5...
Feb 13 18:15:50 ip-172-31-20-33.ap-southeast-2.compute.internal nscd[5427]: 5...
Feb 13 18:15:50 ip-172-31-20-33.ap-southeast-2.compute.internal nscd[5427]: 5...
Feb 13 18:15:50 ip-172-31-20-33.ap-southeast-2.compute.internal nscd[5427]: 5...
Feb 13 18:15:50 ip-172-31-20-33.ap-southeast-2.compute.internal nscd[5427]: 5...
Feb 13 18:15:50 ip-172-31-20-33.ap-southeast-2.compute.internal nscd[5427]: 5...
Feb 13 18:15:50 ip-172-31-20-33.ap-southeast-2.compute.internal nscd[5427]: 5...
Feb 13 18:15:50 ip-172-31-20-33.ap-southeast-2.compute.internal systemd[1]: S...
Hint: Some lines were ellipsized, use -l to show in full.

[ec2-user@ip-172-31-20-33 ~]$ sudo service ntpd start
Redirecting to /bin/systemctl start  ntpd.service

[ec2-user@ip-172-31-20-33 ~]$ service ntpd status
Redirecting to /bin/systemctl status  ntpd.service
● ntpd.service - Network Time Service
   Loaded: loaded (/usr/lib/systemd/system/ntpd.service; disabled; vendor preset: disabled)
   Active: active (running) since Mon 2017-02-13 18:18:23 EST; 10s ago
  Process: 5485 ExecStart=/usr/sbin/ntpd -u ntp:ntp $OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 5486 (ntpd)
   CGroup: /system.slice/ntpd.service
           └─5486 /usr/sbin/ntpd -u ntp:ntp -g
Feb 13 18:18:23 ip-172-31-20-33.ap-southeast-2.compute.internal ntpd[5486]: L...
Feb 13 18:18:23 ip-172-31-20-33.ap-southeast-2.compute.internal ntpd[5486]: L...
Feb 13 18:18:23 ip-172-31-20-33.ap-southeast-2.compute.internal ntpd[5486]: L...
Feb 13 18:18:23 ip-172-31-20-33.ap-southeast-2.compute.internal ntpd[5486]: L...
Feb 13 18:18:23 ip-172-31-20-33.ap-southeast-2.compute.internal ntpd[5486]: L...
Feb 13 18:18:23 ip-172-31-20-33.ap-southeast-2.compute.internal ntpd[5486]: L...
Feb 13 18:18:24 ip-172-31-20-33.ap-southeast-2.compute.internal ntpd[5486]: 0...
Feb 13 18:18:24 ip-172-31-20-33.ap-southeast-2.compute.internal ntpd[5486]: 0...
Feb 13 18:18:24 ip-172-31-20-33.ap-southeast-2.compute.internal ntpd[5486]: 0...
Feb 13 18:18:31 ip-172-31-20-33.ap-southeast-2.compute.internal ntpd[5486]: 0...
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by mfernest** [comment]
Please create one Issue for all the work you do for the Installation lab.

I'll close this Issue since it is redundant.
